### ISSUE TITLE
Upgrade to Rider 231

### ISSUE THREAD

**Issue by asidorowicz** [martinskuta/TestingAssistant#4]
Love the plugin, though it needs to be updated to support the latest version of Rider
I just changed the required SDK in my jar and it seems to work

**Comment by martinskuta** [comment]
Hi, sorry I was on holidays. Glad to hear that you love the plugin!

I plan to update the plugin later today or tomorrow. I will update this issue once it is done. Cheers.

**Comment by martinskuta** [comment]
The SDK was updated to use 2023.1.0 and uploaded to JetBrains plugins marketplace.

ReSharper version is already approved on the marketplace. The version for Rider is currently being approved by JetBrains.. usually takes around half day to appear on the marketplace. You can see the status here: https://plugins.jetbrains.com/plugin/19262-testing-assistant/versions/stable/318676

Closing the issue for now.
